### ISSUE TITLE
About the Acoustic and Visual Token Acquirement

### ISSUE THREAD

**Issue by Columbine21** [Say2L/CENet#1]
作者您好，请问一下您代码中使用的 Acoustic 和 Visual Tokens 是如何和文本对齐（时间维度长度一致）的呢？

因为在您的文中 3.1 3.2章的介绍中 音、视频采用的是非对齐unaligned设置。但是在代码里 audio visual token 确是与文本对齐的设置。请问能否提供一下得到audio visual token 的过程代码。

不胜感激 @Say2L

**Comment by Say2L** [comment]
在CENet论文中，对齐指的是多模态时序数据中相应的文本token、音频帧、视频帧在时间上一一对齐，而且是以文本token长度为基准，比如说文本token长度为10，则音频和视频序列长度应该也为10，且和文本token逐个对应。在我们的实验中，为了方便处理，我们把音频和视频序列的最大长度限制为50，若短于50，则补0，若长于50，可采用采样法或均值法来得到长度为50的序列，而对于文本数据，序列过长则采用截断法，过短则采用填充法，除此之外我们并没有对三个模态的序列做任何强制对齐处理，只是把三个模态的序列长度都保证为50。

**Comment by Columbine21** [comment]
实际上音、视频长度应该远远大于50吧，这样直接截取到 50 是否会导致模型只使用了大概前20%的音视频数据，另：50这个数字是怎么确定的呢？

非常感谢

**Comment by Say2L** [comment]
会采用等间距采样或者均值法来得到长度为50的音视频特征序列，而不是只利用前百分之多少的数据，50是为了保持和文本长度一致，能够在一定程度上减少计算量。

**Comment by Columbine21** [comment]
好的，聚类是在采样之前的特征序列上进行，还是等采样之后再聚类呢？

**Comment by Say2L** [comment]
在采样之前进行聚类建立非文本词汇表，这样效果会更好一点。

**Comment by Columbine21** [comment]
好的，非常感谢。还有一个细节的问题：代码中

https://github.com/Say2L/CENet/blob/204fa293eca3c8150d76e33c3a6b75bd7722190b/train.py#L61

这里模型的各个部分的learning rates 其实设置的都一样（一般会给load上来的模型更小的学习率），这个是怎么考虑的呢？

**Comment by Columbine21** [comment]
另：我自己在训练这个模型的时候发现模型训练速度非常的快，这个是符合预期的么（好像mosi上不到5min就训练完成了，感觉比BERT-MAG 快不少）

**Comment by Say2L** [comment]
> 

的确很快就会训练完，和BERT-MAG我有没有进行过速度方面的比较。

**Comment by Say2L** [comment]
> 好的，非常感谢。还有一个细节的问题：代码中
> 
> https://github.com/Say2L/CENet/blob/204fa293eca3c8150d76e33c3a6b75bd7722190b/train.py#L61
> 
> 这里模型的各个部分的learning rates 其实设置的都一样（一般会给load上来的模型更小的学习率），这个是怎么考虑的呢？

因为在实验中发现使用这个学习率能够得到比较好的结果，这个主要是根据经验进行调试，没有其他的考虑。

**Comment by Columbine21** [comment]
> > 好的，非常感谢。还有一个细节的问题：代码中
> > https://github.com/Say2L/CENet/blob/204fa293eca3c8150d76e33c3a6b75bd7722190b/train.py#L61
> > 
> > 这里模型的各个部分的learning rates 其实设置的都一样（一般会给load上来的模型更小的学习率），这个是怎么考虑的呢？
> 
> 因为在实验中发现使用这个学习率能够得到比较好的结果，这个主要是根据经验进行调试，没有其他的考虑。

如果把CE module 单独设置 比其他的 SentiLARE 模型的结构更小的learning rate会更好么？

**Comment by Say2L** [comment]
> > > 好的，非常感谢。还有一个细节的问题：代码中
> > > https://github.com/Say2L/CENet/blob/204fa293eca3c8150d76e33c3a6b75bd7722190b/train.py#L61
> > > 
> > > 这里模型的各个部分的learning rates 其实设置的都一样（一般会给load上来的模型更小的学习率），这个是怎么考虑的呢？
> > 
> > 
> > 因为在实验中发现使用这个学习率能够得到比较好的结果，这个主要是根据经验进行调试，没有其他的考虑。
> 
> 如果把CE module 单独设置 比其他的 SentiLARE 模型的结构更小的learning rate会更好么？

有尝试过对不同模块使用不同的学习率进行训练，但是没有得到更好的结果。

**Comment by Columbine21** [comment]
> > > > 好的，非常感谢。还有一个细节的问题：代码中
> > > > https://github.com/Say2L/CENet/blob/204fa293eca3c8150d76e33c3a6b75bd7722190b/train.py#L61
> > > > 
> > > > 这里模型的各个部分的learning rates 其实设置的都一样（一般会给load上来的模型更小的学习率），这个是怎么考虑的呢？
> > > 
> > > 
> > > 因为在实验中发现使用这个学习率能够得到比较好的结果，这个主要是根据经验进行调试，没有其他的考虑。
> > 
> > 
> > 如果把CE module 单独设置 比其他的 SentiLARE 模型的结构更小的learning rate会更好么？
> 
> 有尝试过对不同模块使用不同的学习率进行训练，但是没有得到更好的结果。

好的，谢谢解答，很有意思的工作

**Comment by Say2L** [comment]
> > > > > 好的，非常感谢。还有一个细节的问题：代码中
> > > > > https://github.com/Say2L/CENet/blob/204fa293eca3c8150d76e33c3a6b75bd7722190b/train.py#L61
> > > > > 
> > > > > 这里模型的各个部分的learning rates 其实设置的都一样（一般会给load上来的模型更小的学习率），这个是怎么考虑的呢？
> > > > 
> > > > 
> > > > 因为在实验中发现使用这个学习率能够得到比较好的结果，这个主要是根据经验进行调试，没有其他的考虑。
> > > 
> > > 
> > > 如果把CE module 单独设置 比其他的 SentiLARE 模型的结构更小的learning rate会更好么？
> > 
> > 
> > 有尝试过对不同模块使用不同的学习率进行训练，但是没有得到更好的结果。
> 
> 好的，谢谢解答，很有意思的工作

感谢你的认可
