### ISSUE TITLE
关于基于BERT的CENet的复现问题

### ISSUE THREAD

**Issue by LingFengGold** [Say2L/CENet#2]
您好！
很有意思的工作，但我在复现的时候碰到了一些小问题。因为之前的工作都是基于BERT，为了进行公平的比较，我想基于BERT去复现论文中的结果，论文中CENet(B)在MOSI上的ACC结果为84.40/86.74，我使用默认参数得到结果远远达不到，请问得出这个结果的参数以及种子分别都是什么呢？
感谢！

**Comment by Say2L** [comment]
你可以把学习率设为5e-3，batch size设为32，warmup_proportion设为0.5，seed设为5890试试

**Comment by LingFengGold** [comment]
感谢您的回复。我试了一下，模型直接训坏掉了。对于BERT fine-tune来说，5e-3这个学习率会不会太大了

**Comment by Say2L** [comment]
> 感谢您的回复。我试了一下，模型直接训坏掉了。对于BERT fine-tune来说，5e-3这个学习率会不会太大了

不好意思，上面学习率打错了，应该是3e-5

**Comment by LingFengGold** [comment]
您好，我试了一下比论文结果低了2个点。是不是方法对于硬件环境或者参数非常敏感呢？

**Comment by Say2L** [comment]
> 您好，我试了一下比论文结果低了2个点。是不是方法对于硬件环境或者参数非常敏感呢？

每个epoch的测试结果不稳定，我这里是在第13个epoch达到论文中的结果

**Comment by LingFengGold** [comment]
好的，感谢您的回复，我确实复现不出来论文中的结果。请问能否提供MOSEI数据集的相关参数呢？MOSEI数据集的数据量比较大，测试结果不稳定的情况应该不会很明显。

**Comment by Say2L** [comment]
我今天又重新跑了一次实验，按照requirements.txt文件里面所指定的包版本要求，以及之前所说的参数设置，在windows系统上，单张3090显卡，可以得到论文中的结果。至于MOSEI数据集，由于时间太久了而且我的研究方向有所变化，很多以前的实验设置参数和相关文件丢失了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月18日(周五) 中午1:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Say2L/CENet] 关于基于BERT的CENet的复现问题 (Issue #2)




 
好的，感谢您的回复，我确实复现不出来论文中的结果。请问能否提供MOSEI数据集的相关参数呢？MOSEI数据集的数据量比较大，测试结果不稳定的情况应该不会很明显。

**Comment by LingFengGold** [comment]
好的，谢谢您
