### ISSUE TITLE
MOSEI data pkl file

### ISSUE THREAD

**Issue by abdifatah87** [Say2L/CENet#3]
Hi @Say2L,
I am interested in reproducing your results on the MOSEI dataset. Is it possible for you to provide the pkl file via Google drive also?

Kind regards

**Comment by abdifatah87** [comment]
Hi again @Say2L,
I am very interested in reproducing your results on the other datasets and would really appreciate if the features are made available.

**Comment by Say2L** [comment]
> Hi again @Say2L, I am very interested in reproducing your results on the other datasets and would really appreciate if the features are made available.

Hi, the MOSEI pkl is uploaded to the google cloud.
