### ISSUE TITLE
SentiLare_Bert pretrain

### ISSUE THREAD

**Issue by Sean-xiang** [Say2L/CENet#4]
Hi @Say2L,
Is there a pre-trained model for sentilare_bert? not for roberta 

Thanks !!!!

**Comment by Say2L** [comment]
> Hi @Say2L, Is there a pre-trained model for sentilare_bert? not for roberta
> 
> Thanks !!!!


Sorry, we don't have that pre-trained model. The pre-trained weights of sentilare are obtained from its official code.
