### ISSUE TITLE
关于mosei数据集的问题

### ISSUE THREAD

**Issue by hustcselwb** [Say2L/CENet#5]
你好，下载了您提供的mosei数据集之后，读取了一下那个pkl文件，您能否告知数据集pkl文件的具体构造，比如哪些是vision，audio，和text的feature，哪些是label这些信息，期待您的回稿

**Comment by hustcselwb** [comment]
你好，我再次查看了您给的mosei的数据吗，但是里面好像没有text的feature，只有vision和audio的feature

**Comment by Say2L** [comment]
> 你好，我再次查看了您给的mosei的数据吗，但是里面好像没有text的feature，只有vision和audio的feature

是的，提供的pkl文件里面没有对text进行处理，只提供了原始text文本，这样的话方便使用不同的预训练语言模型提取token。
