### ISSUE TITLE
关于mosi数据集

### ISSUE THREAD

**Issue by 695950719** [Say2L/CENet#6]
请问mosi的数据集为什么和平时常用的mosi数据集大小差这么多，有做什么预处理吗

**Comment by hustcselwb** [comment]
没有吧，现在使用的mosi数据集的大小不都是2000出头吗

**Comment by hustcselwb** [comment]
不过现在有些在SIMs和SIMSV2数据集上进行测试，这是两个中文数据集，mosi太老了而且很小

**Comment by 695950719** [comment]
谢谢哥回答。我还想问个问题，文中的用KMEANS的特征转换策略的代码部分在哪 我看了半天没找到。

**Comment by 695950719** [comment]
> 不过现在有些在SIMs和SIMSV2数据集上进行测试，这是两个中文数据集，mosi太老了而且很小

谢谢哥回答。我还想问个问题，文中的用KMEANS的特征转换策略的代码部分在哪 我看了半天没找到。

**Comment by hustcselwb** [comment]
抱歉，我没细看这个模型的代码，所以对于这个问题我没法解答，我只是在找一些sota进行对比，但是我发现他这个文章没有给出bert编码在mosei数据集上的效果，如果你在某些地方看见，请联系我。

**Comment by Say2L** [comment]
> 请问mosi的数据集为什么和平时常用的mosi数据集大小差这么多，有做什么预处理吗

没有做什么特殊的预处理，提供的MOSI数据集应该是这个数据集的正常大小。
